export const coinConfigs = [
  {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    image: "/images/bitcoin.png",
  },
  {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    image: "/images/ethereum.png",
  },
  { id: "tether", name: "Tether", symbol: "USDT", image: "/images/tether.png" },
  {
    id: "usdCoin",
    name: "USD Coin",
    symbol: "USDC",
    image: "/images/usdCoin.png",
  },
  { id: "bnb", name: "BNB", symbol: "BNB", image: "/images/bnb.png" },
  {
    id: "binanceUsd",
    name: "Binance USD",
    symbol: "BUSD",
    image: "/images/binanceUsd.png",
  },
  { id: "xrp", name: "XRP", symbol: "XRP", image: "/images/xrp.png" },
  {
    id: "cardano",
    name: "Cardano",
    symbol: "ADA",
    image: "/images/cardano.png",
  },
  { id: "solana", name: "Solana", symbol: "SOL", image: "/images/solana.png" },
  {
    id: "dogecoin",
    name: "Dogecoin",
    symbol: "DOGE",
    image: "/images/dogecoin.png",
  },
  {
    id: "polkadot",
    name: "Polkadot",
    symbol: "DOT",
    image: "/images/polkadot.png",
  },
  {
    id: "polygon",
    name: "Polygon",
    symbol: "MATIC",
    image: "/images/polygon.png",
  },
  {
    id: "shibaInu",
    name: "Shiba Inu",
    symbol: "SHIB",
    image: "/images/shibaInu.png",
  },
  { id: "dai", name: "Dai", symbol: "DAI", image: "/images/dai.png" },
  {
    id: "avalanche",
    name: "Avalanche",
    symbol: "AVAX",
    image: "/images/avalanche.png",
  },
  { id: "tron", name: "Tron", symbol: "TRX", image: "/images/tron.png" },
  {
    id: "lidoStakedEther",
    name: "Lido Staked Ether",
    symbol: "STETH",
    image: "/images/lidoStakedEther.png",
  },
  {
    id: "wrappedBitcoin",
    name: "Wrapped Bitcoin",
    symbol: "WBTC",
    image: "/images/wrappedBitcoin.png",
  },
  {
    id: "leoToken",
    name: "LEO Token",
    symbol: "LEO",
    image: "/images/leoToken.png",
  },
  {
    id: "litecoin",
    name: "Litecoin",
    symbol: "LTC",
    image: "/images/litecoin.png",
  },
  { id: "ftx", name: "FTX", symbol: "FTT", image: "/images/ftx.png" },
  { id: "okb", name: "OKB", symbol: "OKB", image: "/images/okb.png" },
  {
    id: "uniswap",
    name: "Uniswap",
    symbol: "UNI",
    image: "/images/uniswap.png",
  },
  { id: "cronos", name: "Cronos", symbol: "CRO", image: "/images/cronos.png" },
  {
    id: "chainlink",
    name: "Chainlink",
    symbol: "LINK",
    image: "/images/chainlink.png",
  },
  {
    id: "ethereumClassic",
    name: "Ethereum Classic",
    symbol: "ETC",
    image: "/images/ethereumClassic.png",
  },
  {
    id: "nearProtocol",
    name: "NEAR Protocol",
    symbol: "NEAR",
    image: "/images/nearProtocol.png",
  },
  {
    id: "stellar",
    name: "Stellar",
    symbol: "XLM",
    image: "/images/stellar.png",
  },
  {
    id: "cosmosHub",
    name: "Cosmos Hub",
    symbol: "ATOM",
    image: "/images/cosmosHub.png",
  },
  { id: "monero", name: "Monero", symbol: "XMR", image: "/images/monero.png" },
  // { id: "algorand", name: "Algorand", symbol: "ALGO", image: algorand },
  // {
  //   id: "bitcoinCash",
  //   name: "Bitcoin Cash",
  //   symbol: "BCH",
  //   image: bitcoinCash,
  // },
  // { id: "chain", name: "Chain", symbol: "XCN", image: chain },
  // { id: "thetaFuel", name: "Theta Fuel", symbol: "TFUEL", image: thetaFuel },
  // {
  //   id: "internetComputer",
  //   name: "Internet Computer",
  //   symbol: "ICP",
  //   image: internetComputer,
  // },
  // { id: "apeCoin", name: "ApeCoin", symbol: "APE", image: apeCoin },
  // { id: "veChain", name: "VeChain", symbol: "VET", image: veChain },
  // { id: "flow", name: "Flow", symbol: "FLOW", image: flow },
  // { id: "theSandbox", name: "The Sandbox", symbol: "SAND", image: theSandbox },
  // {
  //   id: "decentraland",
  //   name: "Decentraland",
  //   symbol: "MANA",
  //   image: decentraland,
  // },
  // { id: "tezos", name: "Tezos", symbol: "XTZ", image: tezos },
  // { id: "hedera", name: "Hedera", symbol: "HBAR", image: hedera },
  // { id: "quant", name: "Quant", symbol: "QNT", image: quant },
  // { id: "elrond", name: "Elrond", symbol: "EGLD", image: elrond },
  // { id: "filecoin", name: "Filecoin", symbol: "FIL", image: filecoin },
  // { id: "frax", name: "Frax", symbol: "FRAX", image: frax },
  // { id: "aave", name: "Aave", symbol: "AAVE", image: aave },
  // {
  //   id: "axieInfinity",
  //   name: "Axie Infinity",
  //   symbol: "AXS",
  //   image: axieInfinity,
  // },
  // {
  //   id: "thetaNetwork",
  //   name: "Theta Network",
  //   symbol: "THETA",
  //   image: thetaNetwork,
  // },
  // { id: "trueUsd", name: "TrueUSD", symbol: "TUSD", image: trueUsd },
];
